### ISSUE TITLE
WHO PUSHES BINARY FILES TO GITHUB 

### ISSUE THREAD

**Issue by 7442charles** [MarkVivian/electronics_learning#1]
I couldn't help but notice that you've uploaded a .exe file to the repository. I must say, your dedication to taking us back to the golden age of computing is commendable! However, I seem to have misplaced my binary code translator from 1985. Could you kindly provide us with the Rosetta Stone for this enigmatic masterpiece? Or perhaps a seance to summon the spirits of programmers past? Looking forward to the ASCII version. 🖥️
![WhatsApp Image 2024-05-21 at 8 29 53 AM](https://github.com/MarkVivian/electronics_learning/assets/55584337/0786b79f-40df-4591-9492-56069dd26188)

**Comment by MarkVivian** [comment]
i appreciate your concern .
this was a test to see how observant you are (and to see if you were stalking my github account).
you have earned the "get a life" award and "stop being a creep" badge.
we do not value your input in the slightest .. thank you
